MODULE BM_NLP
  INTERFACE
    SUBROUTINE AGS 
	END SUBROUTINE
    SUBROUTINE FNLP
	END SUBROUTINE

    SUBROUTINE GRAD(N,F,X,Y,GR,N1,N2,H,A,FNLP) 
		INTEGER::A,N
		REAL(8),DIMENSION(N)::X,GR
		REAL(8)::H,Y,F
	END SUBROUTINE GRAD

    SUBROUTINE AP1(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP) 
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G1
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
    END SUBROUTINE AP1

	SUBROUTINE AP2(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G1      
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
  	END SUBROUTINE AP2

	SUBROUTINE AP3(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G1
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
	END SUBROUTINE AP3

  	SUBROUTINE AP4(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G1
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
    END SUBROUTINE AP4

	SUBROUTINE A5(N,X,A,B,F,GRAD,AGS,Y,G,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
	END SUBROUTINE A5

  	SUBROUTINE AP6(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8), DIMENSION(N)::X,A,B,G1
		REAL(8), DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
	END SUBROUTINE AP6

	SUBROUTINE A7(N,X,A,B,F,GRAD,AGS,Y,G,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
	END SUBROUTINE A7

	SUBROUTINE A8(N,X,A,B,F,AGR,AGS,Y,G1,Q,PAR,FNLP)
	    REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
	END SUBROUTINE A8

	SUBROUTINE A83(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8),DIMENSION(N)::X,A,B,G1
		REAL(8),DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
    END SUBROUTINE A83

	SUBROUTINE A84(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
		REAL(8)::Y,F
		INTEGER::Q
		REAL(8), DIMENSION(N)::X,A,B,G1
		REAL(8), DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
    END SUBROUTINE A84

    SUBROUTINE A9(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
    	REAL(8)::Y,F
		INTEGER::Q
		REAL(8), DIMENSION(N)::X,A,B,G1
		REAL(8), DIMENSION(40)::PAR
		EXTERNAL F,FNLP,GRAD,AGS
    END SUBROUTINE A9
!---------------------------------------------------------------------------------------------
	SUBROUTINE UNCONS
    END SUBROUTINE

	SUBROUTINE CGR(F,X,Y,M,GR,K,N1,N2,H,A)
		COMMON /A1/ M1,N
		INTEGER::N1,N2,M,K,A
		REAL(8)::H
		REAL(8),DIMENSION(N)::X,GR
		REAL(8),DIMENSION(M1)::Y
	END SUBROUTINE CGR

	SUBROUTINE CGS(F,X,Y,M,CGR,GR,GS,K,N1,N2,H,A)
		COMMON /A1/  M1,N
		INTEGER::N1,N2,M,K,A
		REAL(8)::H
		REAL(8),DIMENSION(N)::X,GR
		REAL(8),DIMENSION(N,N)::GS
		REAL(8),DIMENSION(M1)::Y
  	END SUBROUTINE CGS

	SUBROUTINE CP1(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q,UNCONS)                
		COMMON /A1/  M1
		INTEGER::N,L,M,Q
  		REAL(8)::F
		REAL(8), DIMENSION(N)::X,A,B
		REAL(8), DIMENSION(M)::P
		REAL(8), DIMENSION(M1)::Y
		REAL(8), DIMENSION(40)::PAR
		EXTERNAL F,CGR,CGS,UNCONS
	END SUBROUTINE CP1

	SUBROUTINE C2(N,L,M,X,A,B,P,F,CGR,CGS,YY,PAR,Q)
        COMMON /A1/  M1
        INTEGER::N,L,M,Q
	    REAL(8)::F
        REAL(8), DIMENSION(40)::PAR
        REAL(8), DIMENSION(N)::A,B,X
        REAL(8), DIMENSION(M)::P
        REAL(8), DIMENSION(M1)::YY
	    EXTERNAL F,CGR,CGS
	END SUBROUTINE C2

	SUBROUTINE CP3(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q,UNCONS)
        COMMON /A1/   M1
        INTEGER::N,L,M,Q
	    REAL(8)::F
        REAL(8), DIMENSION(40)::PAR
        REAL(8), DIMENSION(N)::X,A,B
        REAL(8), DIMENSION(M)::P
        REAL(8), DIMENSION(M1)::Y
		EXTERNAL F,CGR,CGS,UNCONS
  	END SUBROUTINE CP3

  	SUBROUTINE CP4(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q,UNCONS)
		COMMON /A1/   M1
        INTEGER::N,L,M,Q
	    REAL(8)::F
        REAL(8), DIMENSION(40)::PAR
        REAL(8), DIMENSION(N)::X,A,B
        REAL(8), DIMENSION(M)::P
        REAL(8), DIMENSION(M1)::Y
	    EXTERNAL F,CGR,CGS,UNCONS
	END SUBROUTINE CP4

    SUBROUTINE CP5(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q,UNCONS)
		COMMON /A1/    M1
        INTEGER::N,L,M,Q
	    REAL(8)::F
        REAL(8), DIMENSION(40)::PAR
        REAL(8), DIMENSION(N)::X,A,B
        REAL(8), DIMENSION(M)::P
        REAL(8), DIMENSION(M1)::Y
	    EXTERNAL F,CGR,CGS,UNCONS
	END SUBROUTINE CP5

	SUBROUTINE CP6(N,L,M,X,A,B,P,F,CGR,CGS,YY,PAR,Q,UNCONS)
		COMMON /A1/    M1
		INTEGER::N,L,M,Q
		REAL(8)::F
		REAL(8), DIMENSION(40)::PAR
		REAL(8), DIMENSION(N)::X,A,B
		REAL(8), DIMENSION(M)::P
		REAL(8), DIMENSION(M1)::YY
  	    EXTERNAL F,CGR,CGS,UNCONS
	END SUBROUTINE CP6
	
  	SUBROUTINE C7(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q)
		COMMON /A1/  M1
		INTEGER::N,L,M,Q
	    REAL(8)::F
        REAL(8), DIMENSION(40)::PAR
        REAL(8), DIMENSION(N)::A,B,X
        REAL(8), DIMENSION(M)::P
        REAL(8), DIMENSION(M1)::Y
  	    EXTERNAL F,CGR,CGS
    END SUBROUTINE C7

    SUBROUTINE C8(N,L,M,X,A,B,P,F,CGR,CGS,ZNFUNK,PAR,Q,UNCONS)
		COMMON /A1/  M1
        INTEGER::N,L,M,Q
        REAL(8)::F
        REAL(8), DIMENSION(40)::PAR
        REAL(8), DIMENSION(N)::X,A,B
        REAL(8), DIMENSION(M)::P
        REAL(8), DIMENSION(M1)::Y, ZNFUNK
		EXTERNAL F,CGR,CGS,UNCONS
    END SUBROUTINE C8
	
	SUBROUTINE C9(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q)
	    COMMON /A1/  M1
        INTEGER::N,L,M,Q
	    REAL(8)::F
        REAL(8), DIMENSION(40)::PAR
        REAL(8), DIMENSION(N)::X,A,B
        REAL(8), DIMENSION(M)::P
        REAL(8), DIMENSION(M1)::Y
	    EXTERNAL F,CGR,CGS
    END SUBROUTINE C9

    SUBROUTINE BNYTP(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q,UNCONS)
		COMMON /A1/   M1
        INTEGER::N,L,M,Q
	    REAL(8)::F
        REAL(8),DIMENSION(N)::A,B,X
        REAL(8),DIMENSION(M)::P
        REAL(8),DIMENSION(M1)::Y
        REAL(8),DIMENSION(40)::PAR
	    EXTERNAL F,CGR,CGS,UNCONS,AP3
	END SUBROUTINE BNYTP
  END INTERFACE
END MODULE BM_NLP

