C
C              TECTˆPOBAHˆE METO„OB ˆ‡ AKETA M
C              MO„ˆ”ˆ–ˆPOBAHH›‰ METO„ HœžTOHA  ( A8  )
C
C  BHˆMAHˆE: „‹Ÿ OPA™EHˆŸ MATPˆ–› ˆCO‹œ‡“ETCŸ
C            O„POƒPAMMA DMINV.OTOM“ HEOXO„ˆMO
C            O„K‹ž—EHˆE ˆ‹ˆOTEKˆ SSPLIB
C
C        OˆCAHˆE APAMETPOB POƒPAMM› METO„A
C
C      PA‡MEPHOCTœ MACCˆBOB X,A,B,G1  PABHA  N
         REAL *8 X(2),A(2),B(2),G1(2)
         REAL *8 PAR(40),Y
         REAL *8 F,FNLP
         EXTERNAL F,FNLP,GRAD,AGS
         INTEGER Q
C
C           OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
C
         COMMON /A829/ M1/A81  /HES /A82  / P1 /A83  /  P2
     *          /A84 / XV /A85 / FV /A86 / XT /A87 / TR /A88 /L1
C       PA‡MEPHOCTœ  MACCˆBA HES  = N*N
         REAL *8 HES (2 ,2)
C       PA‡MEPHOCTœ  MACCˆBA P2   = 3*N
         REAL *8 P2  (3 ,2)
C       PA‡MEPHOCTœ  BCEX MACCˆBOB  = N
         REAL *8  P1( 2 ),XV( 2 ),L1( 2 ),M1( 2 ),
     *           FV( 2 ),XT( 2 ),TR( 2 )
C
C           XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
C
C     N - PA‡MEPHOCTœ ‡A„A—ˆ
C     X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
C     A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
C     B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
C     F - ˆMŸ O„POƒPAMM› TˆA FUNCTION „‹Ÿ B›—ˆC‹EHˆŸ
C         ‡HA—EHˆŸ KPˆTEPˆŸ
C     GRAD - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ
C         B›—ˆC‹EHˆŸ ƒPA„ˆEHTA  ( ˆCO‹œ‡“ETCŸ CBOŸ
C         BCTPOEHHAŸ POƒPAMMA B›—ˆC‹EHˆŸ ƒPA„ˆEHTA )
C     AGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA
C           MATPˆ–› BTOP›X POˆ‡BO„H›X (HE ˆCO‹œ‡“ETCŸ )
C     Y - ‡HA—EHˆE KPˆTEPˆŸ
C     G1 - BEKTOP ‡HA—EHˆ‰ POˆ‡BO„H›X ”“HK–ˆˆ F
C     Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 0)
C     PAR - BEKTOP APAMETPOB METO„A
C     FNLP - ”ˆKCˆPOBAHHOE ˆMŸ O„POƒPAMM›
C
C         ˆCXO„H›E „AHH›E ‡A„A—ˆ
C
C     PA‡MEPHOCTœ ‡A„A—ˆ
         N=2
C     HA—A‹œHAŸ TO—KA
         X(1)=  1.2
         X(2)=  1.0
C
C    ‡A„AHˆE APAMETPOB METO„A
C
         Q=0
C     TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O HOPME ƒPA„ˆEHTA
         PAR(Q+1)=0.00001
C     MAKCˆMA‹œHOE —ˆC‹O ˜AƒOB,KOTOPOE MO†HO C„E‹ATœ
         PAR(Q+2)=25
C     B›XO„HO‰ APAMETP
         PAR(Q+3)=0
C     Pˆ‡HAK HA—A‹œHO‰ OPE„E‹EHHOCTˆ APAMETPOB Y ˆ G1
C                          ( 0,1 ˆ‹ˆ 2 )
         PAR(Q+4)=0
C     HA—A‹œH›‰ ˜Aƒ C“CKA
         PAR(Q+5)=0.001
C     MA†OPAHTA ƒO‹„CTE‰HA
         PAR(Q+6)=0.45
C     ˜Aƒ KOHE—HO-PA‡HOCTHO‰ APOKCˆMA–ˆˆ POˆ‡BO„H›X
         PAR(Q+7)=0.00001
C     —ˆC‹O “„A—H›X ˜AƒOB,—EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ
C     ˆH”OPMA–ˆž
         PAR(Q+8)=1
C     CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 3 )
         PAR(Q+9)=3
C
         CALL A8 (N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
         END
