! TECTÈPOBAHÈE METOÄOB ÈÇ ÏAKETA ÁM KBÀÇÈÍÜÞÒÎÍÎÂÑÊÈÉ ÌÅÒÎÄ (A84)
PROGRAM VA84
! XAPAKTEPÈCTÈKA ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! N - PAÇMEPHOCTÜ ÇAÄA×È
    ! X - BEKTOP ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! A - BEKTOP ËEBÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË. ÏEPEMEHHÛX
    ! B - BEKTOP ÏPABÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË.ÏEPEMEHHÛX
    ! F - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA FUNCTION ÄËß BÛ×ÈCËEHÈß ÇHA×EHÈß KPÈTEPÈß
    ! GRAD - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÃPAÄÈEHTA
    ! AGS - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß PAC×ETA MATPÈÖÛ BTOPÛX ÏPOÈÇBOÄHÛX (HE ÈCÏOËÜÇÓETCß )
    ! Y - ÇHA×EHÈE KPÈTEPÈß
    ! G1 - BEKTOP ÇHA×EHÈÉ ÏPOÈÇBOÄHÛX ÔÓHKÖÈÈ F
    ! Q - ÏAPAMETP C ÔÈKCÈPOBAHHÛM ÇHA×EHÈEM ( = 0)
    ! PAR - BEKTOP ÏAPAMETPOB METOÄA
    ! FNLP - ÔÈKCÈPOBAHHOE ÈMß ÏOÄÏPOÃPAMMÛ
! OÏÈCAHÈE ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! OÏÈCAHÈE OÁÙÈX OÁËACTEÉ METOÄA
    COMMON /A841/ HES
    COMMON /A842/ P1
    COMMON /A843/ P2
    COMMON /A844/ DGR
    COMMON /A845/ XV
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    ! PAÇMEPHOCTÜ MACCÈBOB X,A,B,G1  PABHA  N
    REAL(8),DIMENSION(40)::PAR
    REAL(8),DIMENSION(2)::X,A,B,G1
    ! PAÇMEPHOCTÜ  MACCÈBA HES  = N*N
    REAL(8),DIMENSION(2,2)::HES
    ! PAÇMEPHOCTÜ BCEX MACCÈBOB  = N
    REAL(8),DIMENSION(2)::P1,P2,DGR ,XV
    EXTERNAL F,FNLP,GRAD,AGS
! ÈCXOÄHÛE ÄAHHÛE ÇAÄA×È
    ! PAÇMEPHOCTÜ ÇAÄA×È
    N=2
    ! HA×AËÜHAß TO×KA
    X(1)=-1.0
    X(2)=-1.0
! ÇAÄAHÈE ÏAPAMETPOB METOÄA
    Q=0
    PAR(Q+1)=0.0001   ! TO×HOCTÜ PEØEHÈß ÇAÄA×È ÏO HOPME ÃPAÄÈEHTA
    PAR(Q+2)=20       ! MAKCÈMAËÜHOE ×ÈCËO ØAÃOB, KOTOPOE MOÆHO CÄEËATÜ
    PAR(Q+3)=0        ! BÛXOÄHOÉ ÏAPAMETP
    PAR(Q+4)=0        ! ÏPÈÇHAK HA×AËÜHOÉ OÏPEÄEËEHHOCTÈ ÏAPAMETPOB Y È G1 ( 0,1 ÈËÈ 2 )
    PAR(Q+5)=0.001    ! HA×AËÜHÛÉ ØAÃ CÏÓCKA
    PAR(Q+6)=0.45     ! MAÆOPAHTA ÃOËÄCTEÉHA
    PAR(Q+7)=4        ! HOMEP BEPCÈÈ METOÄA ( 1,2,3, ÈËÈ 4 )
    PAR(Q+8)=0        ! ÏPÈÇHAK CÏOCOÁA BÛ×ÈCËEHÈß HA×AËÜHOÉ MATPÈÖÛ HAÏPABËEHÈÉ  ( 0 ÈËÈ 1 )
    PAR(Q+9)=2        ! ÏOPßÄOK ÄÈÔÔEPEHÖÈPOBAHÈß ( = 1 ÈËÈ 2 )
    PAR(Q+10)=0.00001 ! ØAÃ ÄÈÔÔEPEHÖÈPOBAHÈß
    PAR(Q+11)=1       ! ÏPÈÇHAK CXEMÛ BÛ×ÈCËEHÈß ÃECCÈAHA, ECËÈ PAR(Q+8)=1;    ( 1,2 ÈËÈ 3 )
    PAR(Q+12)=1       ! ×ÈCËO ÓÄA×HÛX ØAÃOB, ×EPEÇ KOTOPOE CËEÄÓET BÛBOÄÈTÜ ÈHÔOPMAÖÈÞ
    PAR(Q+13)=3       ! CTEÏEHÜ ÏOÄPOÁHOCTÈ BÛBOÄÈMOÉ ÈHÔOPMAÖÈÈ ( OT 0 ÄO 3 )
! ÂÛÇÎÂ ÌÅÒÎÄÀ
         CALL A84(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VA84
