! TECTÈPOBAHÈE METOÄOB ÈÇ ÏAKETA ÁM METOÄ ÏÎÊÎÎÐÄÈÍÀÒÍÎÃÎ ÑÏÓÑÊÀ (AP1)
PROGRAM VAP1
! XAPAKTEPÈCTÈKA ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! N - PAÇMEPHOCTÜ ÇAÄA×È
    ! X - BEKTOP ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! A - BEKTOP ËEBÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË. ÏEPEMEHHÛX
    ! B - BEKTOP ÏPABÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË.ÏEPEMEHHÛX
    ! F - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA FUNCTION ÄËß BÛ×ÈCËEHÈß ÇHA×EHÈß KPÈTEPÈß
    ! GRAD - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÃPAÄÈEHTA
    ! AGS - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß PAC×ETA MATPÈÖÛ BTOPÛX ÏPOÈÇBOÄHÛX (HE ÈCÏOËÜÇÓETCß)
    ! Y - ÇHA×EHÈE KPÈTEPÈß
    ! G1 - BEKTOP ÇHA×EHÈÉ ÏPOÈÇBOÄHÛX ÔÓHKÖÈÈ F
    ! Q - ÏAPAMETP C ÔÈKCÈPOBAHHÛM ÇHA×EHÈEM ( = 0)
    ! PAR - BEKTOP ÏAPAMETPOB METOÄA
    ! FNLP - ÔÈKCÈPOBAHHOE ÈMß ÏOÄÏPOÃPAMMÛ
! OÏÈCAHÈE ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! OÏÈCAHÈE OÁÙÈX OÁËACTEÉ METOÄA
    COMMON /AP11/ X1
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    ! PAÇMEPHOCTÜ MACCÈBOB X,A,B,G1 PABHA N
    REAL(8),DIMENSION(2)::X,A,B,G1
    REAL(8),DIMENSION(40)::PAR
    ! PAÇMEPHOCTÜ  MACCÈBA X1 = N
    REAL(8),DIMENSION(2)::X1
    EXTERNAL F,FNLP,GRAD,AGS
! ÈCXOÄHÛE ÄAHHÛE ÇAÄA×È
    ! PAÇMEPHOCTÜ ÇAÄA×È
    N=2
    ! HA×AËÜHAß TO×KA
    X(1)=0.
    X(2)=0.
    ! ËEBÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    A(1)=-10.
    A(2)=-10.
    ! ÏPABÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    B(1)=10.0
    B(2)=10.0
! ÇAÄAHÈE ÏAPAMETPOB METOÄA
    Q=0 
    PAR(Q+1)=0.000000001 ! TO×HOCTÜ PEØEHÈß ÇAÄA×È ÏO ÈÇMEHEHÈÞ ÔÓHKÖÈOHAËA
    PAR(Q+2)=5000        ! MAKCÈMAËÜHOE ×ÈCËO ØAÃOB, KOTOPOE MOÆHO CÄEËATÜ
    PAR(Q+3)=0           ! BÛXOÄHOÉ ÏAPAMETP
    PAR(Q+4)=1.0         ! HA×AËÜHÛÉ ØAÃ CÏÓCKA
    PAR(Q+5)=0.6         ! MAÆOPAHTA APMÈÉO
    PAR(Q+6)=0.5         ! KOÝÔÔÈÖÈEHT ÓMEHÜØEHÈß ØAÃA
    PAR(Q+7)=0.45        ! MAÆOPAHTA ÃOËÄCTEÉHA
    PAR(Q+8)=6           ! HOMEP BEPCÈÈ METOÄA ( = 1,2,3,4,5 ÈËÈ 6 )
    PAR(Q+9)=0.00001     ! "HEOÏPEÄEËEHHOCTÜ" ÇAÄAHÈß ÃPAHÈÖ ÏAPAËËEËEÏÈÏEÄA
    PAR(Q+10)=1          ! ÏOPßÄOK ÄÈÔÔEPEHÖÈPOBAHÈß ( = 1 ÈËÈ 2 )
    PAR(Q+11)=0.00001    ! ØAÃ ÄÈÔÔEPEHÖÈPOBAHÈß
    PAR(Q+12)=1          ! ×ÈCËO ÓÄA×HÛX ØAÃOB, ×EPEÇ KOTOPOE  CËEÄÓET BÛBOÄÈTÜ ÈHÔOPMAÖÈÞ
    PAR(Q+13)=3          ! CTEÏEHÜ ÏOÄPOÁHOCTÈ BÛBOÄÈMOÉ ÈHÔOPMAÖÈÈ ( OT 0 ÄO 3 )
! ÂÛÇÎÂ ÌÅÒÎÄÀ
    CALL AP1(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VAP1
