! TECTÈPOBAHÈE METOÄOB ÈÇ ÏAKETA ÁM METOÄ ÑÎÏÐßÆ¨ÍÍÛÕ ÃÐÀÄÈÅÍÒÎÂ (AP3)
PROGRAM VAP3
! XAPAKTEPÈCTÈKA ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! N - PAÇMEPHOCTÜ ÇAÄA×È
    ! X - BEKTOP ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! A - BEKTOP ËEBÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË. ÏEPEMEHHÛX
    ! B - BEKTOP ÏPABÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË.ÏEPEMEHHÛX
    ! F - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA FUNCTION ÄËß BÛ×ÈCËEHÈß ÇHA×EHÈß KPÈTEPÈß
    ! GRAD - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÃPAÄÈEHTA
    ! AGS - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß PAC×ETA MATPÈÖÛ BTOPÛX ÏPOÈÇBOÄHÛX (HE ÈCÏOËÜÇÓETCß)
    ! Y - ÇHA×EHÈE KPÈTEPÈß
    ! G1 - BEKTOP ÇHA×EHÈÉ ÏPOÈÇBOÄHÛX ÔÓHKÖÈÈ F
    ! Q - ÏAPAMETP C ÔÈKCÈPOBAHHÛM ÇHA×EHÈEM ( = 0)
    ! PAR - BEKTOP ÏAPAMETPOB METOÄA
    ! FNLP - ÔÈKCÈPOBAHHOE ÈMß ÏOÄÏPOÃPAMMÛ
! OÏÈCAHÈE ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! OÏÈCAHÈE OÁÙÈX OÁËACTEÉ METOÄA
    COMMON /AP31/ P1
    COMMON /AP32/ P2
    COMMON /AP33/ G2
    COMMON /AP34/ XV
    COMMON /AP35/ W
    COMMON /AP36/ WN
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    ! PAÇMEPHOCTÜ MACCÈBOB X,A,B,G1 PABHA N
    REAL(8),DIMENSION(2)::X,A,B,G1
    REAL(8),DIMENSION(40)::PAR
    ! PAÇMEPHOCTÜ BCEX MACCÈBOB = N
    REAL(8),DIMENSION(2)::P1,P2,G2,XV
    INTEGER,DIMENSION(2)::W,WN
    EXTERNAL F,FNLP,GRAD,AGS
! ÈCXOÄHÛE ÄAHHÛE ÇAÄA×È
    ! PAÇMEPHOCTÜ ÇAÄA×È
    N=2
    ! HA×AËÜHAß TO×KA
    X(1)=-1.0
    X(2)=-1.0
    ! ËEBÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    A(1)=-10.
    A(2)=-10.
    ! ÏPABÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    B(1)=10.
    B(2)=10.
! ÇAÄAHÈE ÏAPAMETPOB METOÄA
    Q=0
    PAR(Q+1)=0.001      ! TO×HOCTÜ PEØEHÈß ÇAÄA×È ÏO HOPME ÃPAÄÈEHTA
    PAR(Q+2)=10         ! MAKCÈMAËÜHOE ×ÈCËO ØAÃOB,KOTOPOE MOÆHO CÄEËATÜ
    PAR(Q+3)=0          ! BÛXOÄHOÉ ÏAPAMETP
    PAR(Q+4)=0.0001     ! HA×AËÜHÛÉ ØAÃ CÏÓCKA
    PAR(Q+5)=0.1        ! HA×AËÜHAß TO×HOCTÜ PEØEHÈß OÄHOMEPHOÉ ÇAÄA×È BÛÁOPA OÏTÈMAËÜHOÃO ØAÃA
    PAR(Q+6)=0.00000001 ! MÈHÈMAËÜHÛÉ ØAÃ CÏÓCKA
    PAR(Q+7)=10         ! ×ÈCËO ÈTEPAÖÈÉ,×EPEÇ KOTOPOE METOÄ "BOCCTAHABËÈBAETCß"
    PAR(Q+8)=1          ! HOMEP BEPCÈÈ METOÄA ( = 1 ÈËÈ 2 )
    PAR(Q+9)=2          ! ÏOPßÄOK ÄÈÔÔEPEHÖÈPOBAHÈß ( = 1 ÈËÈ 2 )
    PAR(Q+10)=0.00001   ! ØAÃ ÄÈÔÔEPEHÖÈPOBAHÈß
    PAR(Q+11)=1         ! ×ÈCËO ÓÄA×HÛX ØAÃOB,×EPEÇ KOTOPOE  CËEÄÓET BÛBOÄÈTÜ ÈHÔOPMAÖÈÞ
    PAR(Q+12)=3         ! CTEÏEHÜ ÏOÄPOÁHOCTÈ BÛBOÄÈMOÉ ÈHÔOPMAÖÈÈ: OT 0 ÄO 3
! ÂÛÇÎÂ ÌÅÒÎÄÀ
    CALL AP3(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VAP3
