! TECTÈPOBAHÈE METOÄOB ÈÇ ÏAKETA ÁM METOÄ CËÓ×ÀÉÍÎÃÎ ÏÎÈÑÊÀ (AP6)
PROGRAM VAP6
! XAPAKTEPÈCTÈKA ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! N - PAÇMEPHOCTÜ ÇAÄA×È
    ! X - BEKTOP ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! A - BEKTOP ËEBÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË. ÏEPEMEHHÛX
    ! B - BEKTOP ÏPABÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË.ÏEPEMEHHÛX
    ! F - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA FUNCTION ÄËß BÛ×ÈCËEHÈß ÇHA×EHÈß KPÈTEPÈß
    ! GRAD - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÃPAÄÈEHTA (HE ÈCÏOËÜÇÓETCß)
    ! AGS - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß PAC×ETA MATPÈÖÛ BTOPÛX ÏPOÈÇBOÄHÛX (HE ÈCÏOËÜÇÓETCß)
    ! Y - ÇHA×EHÈE KPÈTEPÈß
    ! G1 - BEKTOP ÇHA×EHÈÉ ÏPOÈÇBOÄHÛX ÔÓHKÖÈÈ F
    ! Q - ÏAPAMETP C ÔÈKCÈPOBAHHÛM ÇHA×EHÈEM ( = 0)
    ! PAR - BEKTOP ÏAPAMETPOB METOÄA
    ! FNLP - ÔÈKCÈPOBAHHOE ÈMß ÏOÄÏPOÃPAMMÛ
! OÏÈCAHÈE ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! OÏÈCAHÈE OÁÙÈX OÁËACTEÉ METOÄA
    COMMON /AP61/ Z1
    COMMON /AP62/ XM
    COMMON /AP63/ W
    COMMON /AP64/ WM
    COMMON /AP65/ X1
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    ! PAÇMEPHOCTÜ MACCÈBOB X,A,B,G1  PABHA  N
    REAL(8),DIMENSION(2)::X,A,B,G1
    REAL(8),DIMENSION(40)::PAR
    ! PAÇMEPHOCTÜ BCEX MACCÈBOB = N
    REAL(8),DIMENSION(2)::Z1,XM,W,WM,X1
    EXTERNAL F,FNLP,GRAD,AGS
! ÈCXOÄHÛE ÄAHHÛE ÇAÄA×È
    ! PAÇMEPHOCTÜ ÇAÄA×È
    N=2
    ! HA×AËÜHAß TO×KA
    X(1)=-1.0
    X(2)=-1.0
    ! ËEBÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    A(1)=-10.
    A(2)=-10.
    ! ÏPABÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    B(1)=10.
    B(2)=10.
! ÇAÄAHÈE ÏAPAMETPOB METOÄA
    Q=0
    PAR(1)=0.0001   ! TO×HOCTÜ PEØEHÈß ÇAÄA×È
    PAR(2)=500      ! MAKCÈMAËÜHOE ×ÈCËO ØAÃOB,KOTOPOE MOÆHO CÄEËATÜ
    PAR(3)=0        ! BÛXOÄHOÉ ÏAPAMETP
    PAR(4)=0.1      ! HA×AËÜHÛÉ ØAÃ CÏÓCKA
    PAR(5)=1.5      ! KOÝÔÔÈÖÈEHT ÓBEËÈ×EHÈß ØAÃA CÏÓCKA
    PAR(6)=0.903602 ! KOÝÔÔÈÖÈEHT ÓMEHÜØEHÈß ØAÃA CÏÓCKA
    PAR(7)=5.0      ! ÏAPAMETP ÈÇMEHEHÈß ÏËOTHOCTÈ PACÏPEÄEËEHÈß
    PAR(8)=10       ! ×ÈCËO ÓÄA×HÛX ØAÃOB,×EPEÇ KOTOPOE MEHßETCß ÏËOTHOCTÜ PACÏPEÄEËEHÈß CËÓ×AÉHÛX ×ÈCEË
    PAR(9) =20      ! OÁÙEE ×ÈCËO ØAÃOB,×EPEÇ KOTOPOE MEHßETCß ÏËOTHOCTÜ PACÏPEÄEËEHÈß CËÓ×AÉHÛX ×ÈCEË
    PAR(10)= 13579  ! HE×ETHOE ×ÈCËO ÈÇ ÈHTEPBAËA (1;67108863) ÄËß ÇAÏÓCKA ÃEHEPATOPA CËÓ×AÉHÛX ×ÈCEË
    PAR(11)=1       ! ×ÈCËO ÓÄA×HÛX ØAÃOB,×EPEÇ KOTOPOE  CËEÄÓET BÛBOÄÈTÜ ÈHÔOPMAÖÈÞ
    PAR(12)=3       ! CTEÏEHÜ ÏOÄPOÁHOCTÈ BÛBOÄÈMOÉ ÈHÔOPMAÖÈÈ: OT 0 ÄO 3
! ÂÛÇÎÂ ÌÅÒÎÄÀ
    CALL AP6(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VAP6
