! ÈCÏOËÜÇOBAHÈE METOÄOB ÈÇ ÏAKETA OÏTÈMÈÇAÖÈÈ HËÏ METOÄ ËÈÍÅÀÐÈÇÀÖÈÈ (C2)
PROGRAM VC2
! XAPAKTEPÈCTÈKA ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! N - PAÇMEPHOCTÜ BEKTOPA ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! L - ×ÈCËO OÃPAHÈ×EHÈÉ TÈÏA PABEHCTB
    ! M - OÁÙEE ×ÈCËO OÃPAHÈ×EHÈÉ
    ! X - BEKTOP ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! A - BEKTOP ËEBÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË. ÏEPEMEHHÛX
    ! B - BEKTOP ÏPABÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË.ÏEPEMEHHÛX
    ! P - BEKTOP ÄBOÉCTBEHHÛX ÏEPEMEHHÛX
    ! F - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÇHA×EHÈß KPÈTEPÈß È OÃPAHÈ×EHÈÉ
    ! CGR - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÃPAÄÈEHTOB ÖEËEBOÉ ÔÓHKÖÈÈ È OÃPAHÈ×EHÈÉ
    ! CGS - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß PAC×ETA MATPÈÖÛ BTOPÛX ÏPOÈÇBOÄHÛX ÖEËEBOÉ ÔÓHKÖÈÈ È OÃPAHÈ×EHÈÉ
    ! Y - BEKTOP ÇHA×EHÈÉ KPÈTEPÈß È OÃPAHÈ×EHÈÉ
    ! PAR - BEKTOP ÏAPAMETPOB METOÄA
    ! Q - ÏAPAMETP C ÔÈKCÈPOBAHHÛM ÇHA×EHÈEM (= 20)
    ! UNCONS -  ÈMß ÏOÄÏPOÃPAMMÛ METOÄA ÁEÇÓCËOBHOÉ MÈHÈMÈÇAÖÈÈ
! OÏÈCAHÈE ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! OÏÈCAHÈE OÁÙÈX OÁËACTEÉ METOÄA
    COMMON /A1/  M1,N,L
    COMMON /A2/  GR
    COMMON /A3/  GRF
    COMMON /A4/  HX
    COMMON /A5/  XQ
    COMMON /A6/  U
    COMMON /A7/  YQ
    COMMON /A8/  Y1
    COMMON /A9/  Y2
    COMMON /A11/ ES
    COMMON /A10/ NF
    COMMON /A12/ IS
    COMMON /A13/ IT
    COMMON /A20/ SM
    COMMON /A21/ SN
    COMMON /A22/ U1
    COMMON /A23/ Y11
    INTEGER::N,L,M1,Q,M,VAR,NF
    REAL(8)::F
    ! PAÇMEPHOCTÜ MACCÈBOB X,A,B PABHA N
    REAL(8),DIMENSION(3)::X,A,B
    ! PAÇMEPHOCTÜ MACCÈBA P PABHA M
    REAL(8),DIMENSION(5)::P
    ! PAÇMEPHOCTÜ MACCÈBA Y PABHA M1=M+1
    REAL(8),DIMENSION(6)::Y
    REAL(8),DIMENSION(40)::PAR
    ! PAÇMEPHOCTÜ MACCÈBOB GR,GRF,HX,XQ,IT = N
    REAL(8),DIMENSION(3)::GR,GRF,HX,XQ
    INTEGER,DIMENSION(3)::IT
    ! PAÇMEPHOCTÜ MACCÈBOBA U,IS = M
    REAL(8),DIMENSION(5)::U
    INTEGER,DIMENSION(5)::IS
    ! PAÇMEPHOCTÜ MACCÈBOB YQ,Y1,Y2 = M1
    REAL(8),DIMENSION(6)::YQ,Y1,Y2
    ! PAÇMEPHOCTÜ MACCÈBOB Y11,SN = ( MAX(N+1,M1) )
    REAL(8),DIMENSION(6)::Y11
    INTEGER,DIMENSION(6)::SN
    ! PAÇMEPHOCTÜ MACCÈBA ES = ( MAX(N+2,M+2),2N+M+L+1 )
    REAL(8),DIMENSION(7,13)::ES
    ! PAÇMEPHOCTÜ MACCÈBOB U1,SM = ( MAX(2N+1,M+L+2N) )
    REAL(8),DIMENSION(12)::U1
    INTEGER,DIMENSION(12)::SM
    EXTERNAL F,CGR,CGS
! ÈCXOÄHÛE ÄAHHÛE ÇAÄA×È
    ! PAÇMEPHOCTÜ ÇAÄA×È
    M1=4
    M=M1-1
    L=0
    N=2
    ! HA×AËÜHAß TO×KA
    X(1)=0.5
    X(2)=0.7
    ! ËEBÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    A(1)=-100000.
    A(2)=-100000.
    ! ÏPABÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    B(1)=100000.
    B(2)=100000.
    ! ÄËß ÄAHHOÃO METOÄA  MACCÈBÛ A È B HE ÈCÏOËÜÇÓÞTCß
! ÇHA×EHÈß ÄBOÉCTBEHHÛX ÏEPEMEHHÛX
    P(1)=1.D0
    P(2)=1.D0
    P(3)=0.D0
    P(4)=0.D0
    P(5)=0.D0
! ÇAÄAHÈE ÏAPAMETPOB METOÄA
    NF=0
    Q=20
    PAR(1)=0.0001 ! TO×HOCTÜ PEØEHÈß ÇAÄA×È
    PAR(2)=1000   ! MAKCÈMAËÜHO BOÇMOÆHOE ×ÈCËO ÈTEPAÖÈÉ
    PAR(3)=0      ! ÔAKTÈ×ECKÈ CÄEËAHHOE ×ÈCËO ÈTEPAÖÈÉ
    PAR(4)=1      ! HOMEP CÏOCOÁA PEØEHÈß ËÈHEÉHÛX ÇAÄA× ( = 1 ÈËÈ 2 )
    PAR(5)=0.1    ! BEC OÃPAHÈ×EHÈÉ B ÓCËOBÈÈ OCTAHOBA METOÄA ( > 0 )
    PAR(6)=1.     ! HA×AËÜHÛÉ ØAÃ CÏÓCKA ( > 0 )
    PAR(7)=10.    ! HA×AËÜHOE ÇHA×EHÈE KOÝÔÔÈÖÈEHTA ØTPAÔA ( > 0 )
    PAR(8)=0.05   ! HA×AËÜHOE ÇHA×EHÈE ÄOÏÓCTÈMOÃO HAPÓØEHÈß OÃPAHÈ×EHÈÉ ( > 0 )
    PAR(9)=0.0001 ! ØAÃ ×ÈCËEHHOÃO ÄÈÔÔEPEHÖÈPOBAHÈß
    PAR(10)=1     ! HOMEP CXEMÛ ×ÈCËEHHOÃO ÄÈÔÔEPEHÖÈPOBAHÈß ( = 1 ÈËÈ 2 )
    PAR(11)=1     ! ×ÈCËO ØAÃOB,×EPEÇ KOTOPOE CËEÄÓET BÛBOÄÈTÜ ÈHÔOPMAÖÈÞ
    PAR(12)=4     ! CTEÏEHÜ ÏOÄPOÁHOCTÈ BÛBOÄÈMOÉ ÈHÔOPMAÖÈÈ ( OT 0 ÄO 4 )
!
    CALL C2(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q)
END PROGRAM VC2
