! METOÄ ÂÎÇÌÎÆÍÛÕ ÍÀÏÐÀÂËÅÍÈÉ (CP1)
PROGRAM VCP1
! XAPAKTEPÈCTÈKA ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! N - PAÇMEPHOCTÜ BEKTOPA ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! L - ×ÈCËO OÃPAHÈ×EHÈÉ TÈÏA PABEHCTB
    ! M - OÁÙEE ×ÈCËO OÃPAHÈ×EHÈÉ
    ! X - BEKTOP ÓÏPABËßEMÛX ÏEPEMEHHÛX
    ! A - BEKTOP ËEBÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË. ÏEPEMEHHÛX
    ! B - BEKTOP ÏPABÛX ÃPAHÈÖ ÈÇMEHEHÈß ÓÏPABË.ÏEPEMEHHÛX
    ! P - BEKTOP ÄBOÉCTBEHHÛX ÏEPEMEHHÛX
    ! F - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÇHA×EHÈß KPÈTEPÈß È OÃPAHÈ×EHÈÉ
    ! CGR - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß BÛ×ÈCËEHÈß ÃPAÄÈEHTOB ÖEËEBOÉ ÔÓHKÖÈÈ È OÃPAHÈ×EHÈÉ
    ! CGS - ÈMß ÏOÄÏPOÃPAMMÛ TÈÏA SUBROUTINE ÄËß PAC×ETA MATPÈÖÛ BTOPÛX ÏPOÈÇBOÄHÛX ÖEËEBOÉ ÔÓHKÖÈÈ È OÃPAHÈ×EHÈÉ
    ! Y - BEKTOP ÇHA×EHÈÉ KPÈTEPÈß È OÃPAHÈ×EHÈÉ
    ! PAR - BEKTOP ÏAPAMETPOB METOÄA
    ! Q - ÏAPAMETP C ÔÈKCÈPOBAHHÛM ÇHA×EHÈEM ( = 20)
    ! UNCONS -  ÈMß ÏOÄÏPOÃPAMMÛ METOÄA ÁEÇÓCËOBHOÉ MÈHÈMÈÇAÖÈÈ
! OÏÈCAHÈE ÏAPAMETPOB ÏPOÃPAMMÛ METOÄA
    ! OÏÈCAHÈE OÁÙÈX OÁËACTEÉ METOÄA
    COMMON /A1/  M1,N,L
    COMMON /A2/  IS
    COMMON /A3/  XA
    COMMON /A4/  HX
    COMMON /A5/  D1
    COMMON /A6/  D2
    COMMON /A7/  GR
    COMMON /A8/  Y1
    COMMON /A9/  Y2
    COMMON /A10/ NF
    COMMON /A11/ ES
    COMMON /A12/ A1
    COMMON /A13/ A2
    COMMON /A14/ YA
    COMMON /A20/ SM
    COMMON /A21/ SN
    COMMON /A22/ U1
    COMMON /A23/ Y11
    REAL(8)::F
    INTEGER::N,L,M1,Q,M,NF
    ! PAÇMEPHOCTÜ MACCÈBOB X,A,B PABHA N
    REAL(8),DIMENSION(2)::X,A,B
    ! PAÇMEPHOCTÜ MACCÈBA P PABHA M
    REAL(8),DIMENSION(3)::P
    ! PAÇMEPHOCTÜ MACCÈBA Y PABHA M1=M+1
    REAL(8),DIMENSION(4)::Y
    REAL(8),DIMENSION(40)::PAR
    ! PAÇMEPHOCTÜ MACCÈBOB XA,GR,HX,D1,D2 = N
    REAL(8),DIMENSION(2)::XA,HX,D1,D2,GR
    ! PAÇMEPHOCTÜ MACCÈBOB U1,SM = N+1
    REAL(8),DIMENSION(3)::U1
    INTEGER,DIMENSION(4)::SM
    ! PAÇMEPHOCTÜ MACCÈBOB YA,Y1,Y2 = M+1
    REAL(8),DIMENSION(4)::YA,Y1,Y2
    ! PAÇMEPHOCTÜ MACCÈBA ES = ( N+M+2,N+2 )
    REAL(8),DIMENSION(10,5)::ES
    ! PAÇMEPHOCTÜ MACCÈBA A1 = ( N+1,N+2 )
    REAL(8),DIMENSION(4,5)::A1
    ! PAÇMEPHOCTÜ MACCÈBA A2 = ( L+1,N+2 )
    REAL(8),DIMENSION(2,5)::A2
    ! PAÇMEPHOCTÜ MACCÈBOB Y11,SN = N+M+1
    REAL(8),DIMENSION(9)::Y11
    INTEGER,DIMENSION(9)::SN
    ! PAÇMEPHOCTÜ MACCÈBA IS = ( M+2 )
    INTEGER,DIMENSION(7)::IS
    EXTERNAL F,CGR,CGS
! 
    NF=0
    Q=20
! ÈCXOÄHÛE ÄAHHÛE ÇAÄA×È
    ! PAÇMEPHOCTÜ ÇAÄA×È
    M1=4
    M=M1-1
    L=0
    N=2
    ! HA×AËÜHAß TO×KA
    X(1)=0.3
    X(2)=0.7
    ! ËEBÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    A(1)=-100000.
    A(2)=-100000.
    ! ÏPABÛE ÃPAHÈÖÛ ÓÏPABË. ÏEPEMEHHÛX ÏO KAÆÄOÉ KOOPÄÈHATE
    B(1)=100000.
    B(2)=100000.
! ÇHA×EHÈß ÄBOÉCTBEHHÛX ÏEPEMEHHÛX
    P(1)=1.D0
    P(2)=1.D0
    P(3)=0.D0
! ÇAÄAHÈE ÏAPAMETPOB METOÄA
    PAR(1)=0.0001 ! TO×HOCTÜ PEØEHÈß ÇAÄA×È
    PAR(2)=110.   ! MAKCÈMAËÜHO BOÇMOÆHOE ×ÈCËO ÈTEPAÖÈÉ
    PAR(3)=0.     ! ÔAKTÈ×ECKÈ CÄEËAHHOE ×ÈCËO ÈTEPAÖÈÉ
    PAR(4)=1.     ! HOMEP BEPCÈÈ METOÄA ( = 1 ÈËÈ 2 )
    PAR(5)=0.1    ! BEÑ OÃPAHÈ×EHÈÉ B ÓCËOBÈÈ OCTAHOBA METOÄA ( > 0 )
    PAR(6)=5.     ! ÏAPAMETP BËÈßHÈß ÖEËEBOÉ ÔÓHKÖÈÈ HA BÛÁOP HAÏPABËEHÈß BO BCÏOMOÃATEËÜHÛX ÇAÄA×AX
    PAR(7)=1.     ! HA×AËÜHÛÉ ØAÃ CÏÓCKA ( > 0 )
    PAR(8)=0.1    ! HA×AËÜHOE ÇHA×EHÈE ÄOÏÓCTÈMOÃO HAPÓØEHÈß OÃPAHÈ×EHÈÉ ( > 0 )
    PAR(9)=0.0001 ! ØAÃ ×ÈCËEHHOÃO ÄÈÔÔEPEHÖÈPOBAHÈß
    PAR(10)=1.    ! HOMEP CXEMÛ ×ÈCËEHHOÃO ÄÈÔÔEPEHÖÈPOBAHÈß ( = 1 ÈËÈ 2 )
    PAR(11)=1.    ! ×ÈCËO ØAÃOB, ×EPEÇ KOTOPOE CËEÄÓET BÛBOÄÈTÜ ÈHÔOPMAÖÈÞ
    PAR(12)=4.    ! CTEÏEHÜ ÏOÄPOÁHOCTÈ BÛBOÄÈMOÉ ÈHÔOPMAÖÈÈ ( OT 0 ÄO 4 )
! ÂÛÇÎÂ ÌÅÒÎÄÀ
    CALL CP1(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q)
END PROGRAM VCP1
