! TECTˆPOBAHˆE METO„OB ˆ‡ AKETA M Œ…’Ž„ €“‹‹€ (A5)
PROGRAM VA5
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ ‡A„A—ˆ
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA FUNCTION „‹Ÿ B›—ˆC‹EHˆŸ ‡HA—EHˆŸ KPˆTEPˆŸ
    ! GRAD - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ƒPA„ˆEHTA ( HE ˆCO‹œ‡“ETCŸ )
    ! AGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA MATPˆ–› BTOP›X POˆ‡BO„H›X (HE ˆCO‹œ‡“ETCŸ )
    ! Y - ‡HA—EHˆE KPˆTEPˆŸ
    ! G1 - BEKTOP ‡HA—EHˆ‰ POˆ‡BO„H›X ”“HK–ˆˆ F
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 0)
    ! PAR - BEKTOP APAMETPOB METO„A
    ! FNLP - ”ˆKCˆPOBAHHOE ˆMŸ O„POƒPAMM›
! OˆCAHˆE APAMETPOB POƒPAMM› METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /A51/ T
    COMMON /A52/ Z
    COMMON /A53/ V
    COMMON /A54/ Q0
    COMMON /A55/ Q1
    COMMON /A56/ E1
    COMMON /A57/ XI
    REAL(8)::Y,F,FNLP
    INTEGER::Q
    ! PA‡MEPHOCTœ MACCˆBOB X,A,B,G1  PABHA  N
    REAL(8),DIMENSION(2)::X,A,B,G1
    REAL(8),DIMENSION(40)::PAR
    ! PA‡MEPHOCTœ BCEX MACCˆBOB  = N
    REAL(8),DIMENSION(2)::T,Z,Q0,Q1,E1,XI
    ! PA‡MEPHOCTœ MACCˆBA V = N*N
    REAL(8),DIMENSION(2,2)::V
    EXTERNAL F,FNLP,GRAD,AGS
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=-1.0
    X(2)=-1.0
! ‡A„AHˆE APAMETPOB METO„A
    Q=0
    PAR(Q+1)=0.00001 ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O ˆ‡MEHEHˆž BEKTOPA X
    PAR(Q+2)=20    ! MAKCˆMA‹œHOE —ˆC‹O ˜AƒOB, KOTOPOE MO†HO C„E‹ATœ
    PAR(Q+3)=0     ! B›XO„HO‰ APAMETP
    PAR(Q+4)=0.5   ! HA—A‹œH›‰ ˜Aƒ C“CKA
    PAR(Q+5)=1.    ! KO””ˆ–ˆEHT MAC˜TAˆPOBAHˆŸ
    PAR(Q+6)=1     ! BEPCˆŸ METO„A ( 1 ˆ‹ˆ 2 )
    PAR(Q+7)=1     ! —ˆC‹O “„A—H›X ˜AƒOB,—EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(Q+8)=3     ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 3 )
    PAR(Q+9)=2     ! —ˆC‹O ˆTEPA–ˆ‰ E‡ “‹“—˜EHˆŸ, OC‹E KOTOPOƒO METO„ ‡AKAH—ˆBAET PAOT“
! ‚›‡Ž‚ Œ…’Ž„€
    CALL A5(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VA5
