! TECTˆPOBAHˆE METO„OB ˆ‡ AKETA M MO„ˆ”ˆ–ˆPOBAHH›‰ METO„ HœžTOHA (A8)
! BHˆMAHˆE: „‹Ÿ OPA™EHˆŸ MATPˆ–› ˆCO‹œ‡“ETCŸ O„POƒPAMMA DMINV. OTOM“ HEOXO„ˆMO O„K‹ž—EHˆE ˆ‹ˆOTEKˆ SSPLIB
PROGRAM VA8
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ ‡A„A—ˆ
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA FUNCTION „‹Ÿ B›—ˆC‹EHˆŸ
    ! ‡HA—EHˆŸ KPˆTEPˆŸ
    ! GRAD - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ
    ! B›—ˆC‹EHˆŸ ƒPA„ˆEHTA  ( ˆCO‹œ‡“ETCŸ CBOŸ
    ! BCTPOEHHAŸ POƒPAMMA B›—ˆC‹EHˆŸ ƒPA„ˆEHTA )
    ! AGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA
    ! MATPˆ–› BTOP›X POˆ‡BO„H›X (HE ˆCO‹œ‡“ETCŸ )
    ! Y - ‡HA—EHˆE KPˆTEPˆŸ
    ! G1 - BEKTOP ‡HA—EHˆ‰ POˆ‡BO„H›X ”“HK–ˆˆ F
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 0)
    ! PAR - BEKTOP APAMETPOB METO„A
    ! FNLP - ”ˆKCˆPOBAHHOE ˆMŸ O„POƒPAMM›
! OˆCAHˆE APAMETPOB POƒPAMM› METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /A81/  HES
    COMMON /A82/  P1
    COMMON /A83/  P2
    COMMON /A84/  XV
    COMMON /A85/  FV
    COMMON /A86/  XT
    COMMON /A87/  TR
    COMMON /A88/  L1
    COMMON /A829/ M1
    ! PA‡MEPHOCTœ MACCˆBOB X,A,B,G1  PABHA  N
    REAL(8),DIMENSION(2)::X,A,B,G1
    REAL(8),DIMENSION(40)::PAR
    ! PA‡MEPHOCTœ  MACCˆBA HES  = N*N
    REAL(8),DIMENSION(2,2)::HES
    ! PA‡MEPHOCTœ  MACCˆBA P2   = 3*N
    REAL(8),DIMENSION(3,2)::P2
    ! PA‡MEPHOCTœ  BCEX MACCˆBOB  = N
    REAL(8),DIMENSION(2)::P1,XV,L1,M1,FV,XT,TR
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    EXTERNAL F,FNLP,GRAD,AGS
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=  1.2
    X(2)=  1.0
! ‡A„AHˆE APAMETPOB METO„A
    Q=0
    PAR(Q+1)=0.00001 ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O HOPME ƒPA„ˆEHTA
    PAR(Q+2)=25      ! MAKCˆMA‹œHOE —ˆC‹O ˜AƒOB,KOTOPOE MO†HO C„E‹ATœ
    PAR(Q+3)=0       ! B›XO„HO‰ APAMETP
    PAR(Q+4)=0       ! Pˆ‡HAK HA—A‹œHO‰ OPE„E‹EHHOCTˆ APAMETPOB Y ˆ G1 ( 0,1 ˆ‹ˆ 2 )
    PAR(Q+5)=0.001   ! HA—A‹œH›‰ ˜Aƒ C“CKA
    PAR(Q+6)=0.45    ! MA†OPAHTA ƒO‹„CTE‰HA
    PAR(Q+7)=0.00001 ! ˜Aƒ KOHE—HO-PA‡HOCTHO‰ APOKCˆMA–ˆˆ POˆ‡BO„H›X
    PAR(Q+8)=1       ! —ˆC‹O “„A—H›X ˜AƒOB,—EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(Q+9)=3       ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 3 )
! ‚›‡Ž‚ Œ…’Ž„€
    CALL A8 (N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VA8