! TECTˆPOBAHˆE METO„OB ˆ‡ AKETA M METO„ HœžTOHA (A‹ƒOPˆTM ˆPžKOBA A.ƒ.) (A83)
PROGRAM VA83
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ ‡A„A—ˆ
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA FUNCTION „‹Ÿ B›—ˆC‹EHˆŸ ‡HA—EHˆŸ KPˆTEPˆŸ
    ! GRAD - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ƒPA„ˆEHTA (ˆCO‹œ‡“ETCŸ CBOŸ BCTPOEHHAŸ POƒPAMMA B›—ˆC‹EHˆŸ ƒPA„ˆEHTA)
    ! AGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA MATPˆ–› BTOP›X POˆ‡BO„H›X (HE ˆCO‹œ‡“ETCŸ)
    ! Y - ‡HA—EHˆE KPˆTEPˆŸ
    ! G1 - BEKTOP ‡HA—EHˆ‰ POˆ‡BO„H›X ”“HK–ˆˆ F
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 0)
    ! PAR - BEKTOP APAMETPOB METO„A
    ! FNLP - ”ˆKCˆPOBAHHOE ˆMŸ O„POƒPAMM›
! OˆCAHˆE APAMETPOB POƒPAMM› METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /A830/ M1
    COMMON /A831/ HESP
    COMMON /A832/ G2
    COMMON /A833/ P1
    COMMON /A834/ P2
    COMMON /A835/ XV
    COMMON /A836/ FV
    COMMON /A837/ XT
    COMMON /A838/ TR
    COMMON /A839/ L1
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    ! PA‡MEPHOCTœ MACCˆBOB X,A,B,G1 PABHA N
    REAL(8),DIMENSION(2)::X,A,B,G1
    REAL(8),DIMENSION(40)::PAR
    ! PA‡MEPHOCTœ BCEX MACCˆBOB = N
    REAL(8),DIMENSION(2)::HESP,G2,P1,P2,XV,FV,XT,TR,L1,M1
    EXTERNAL F,FNLP,GRAD,AGS
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=-1.0
    X(2)=-1.0
! ‡A„AHˆE APAMETPOB METO„A
    Q=0
    PAR(Q+1)=0.0001  ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O HOPME ƒPA„ˆEHTA
    PAR(Q+2)=20      ! MAKCˆMA‹œHOE —ˆC‹O ˜AƒOB, KOTOPOE MO†HO C„E‹ATœ
    PAR(Q+3)=0       ! B›XO„HO‰ APAMETP
    PAR(Q+4)=0       ! Pˆ‡HAK HA—A‹œHO‰ OPE„E‹EHHOCTˆ APAMETPOB Y ˆ G1 ( 0,1 ˆ‹ˆ 2 )
    PAR(Q+5)=0.001   ! HA—A‹œH›‰ ˜Aƒ C“CKA B„O‹œ ƒPA„ˆEHTA
    PAR(Q+6)=0.49    ! MA†OPAHTA ƒO‹„CTE‰HA ( B ˆHTEPBA‹E [0.000001;0.499999] )
    PAR(Q+7)=0       ! KO‹ˆ—ECTBO ˆTEPA–ˆ‰ „‹Ÿ OCTPOEHˆŸ TEK“™EƒO HAPAB‹EHˆŸ OˆCKA KCTPEM“MA; EC‹ˆ =0 ,TO „E‹AETCŸ N ˆTEPA–ˆ‰
    PAR(Q+8)=2       ! OPŸ„OK „ˆ””EPEH–ˆPOBAHˆŸ ( = 1 ˆ‹ˆ 2 )
    PAR(Q+9)=0.00001 ! ˜Aƒ KOHE—HO-PA‡HOCTHO‰ APOKCˆMA–ˆˆ POˆ‡BO„H›X
    PAR(Q+10)=1      ! —ˆC‹O “„A—H›X ˜AƒOB, —EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(Q+11)=3      ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 3 )
! ‚›‡Ž‚ Œ…’Ž„€
    CALL A83(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VA83
