! TECTˆPOBAHˆE METO„OB ˆ‡ AKETA M METO„ ‹‹ˆCOˆ„OB (A9)
PROGRAM VA9
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ ‡A„A—ˆ
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA FUNCTION „‹Ÿ B›—ˆC‹EHˆŸ ‡HA—EHˆŸ KPˆTEPˆŸ
    ! GRAD - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ƒPA„ˆEHTA
    ! AGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA MATPˆ–› BTOP›X POˆ‡BO„H›X (HE ˆCO‹œ‡“ETCŸ )
    ! Y - ‡HA—EHˆE KPˆTEPˆŸ
    ! G1 - BEKTOP ‡HA—EHˆ‰ POˆ‡BO„H›X ”“HK–ˆˆ F
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 0)
    ! PAR - BEKTOP APAMETPOB METO„A
    ! FNLP - ”ˆKCˆPOBAHHOE ˆMŸ O„POƒPAMM›
! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /A91/ BG
    COMMON /A92/ G
    COMMON /A93/ G2
    COMMON /A94/ GN
    COMMON /A95/ XN 
    COMMON /A96/ X1
    ! PA‡MEPHOCTœ MACCˆBOB BCEX MACCˆBOB PABHA N
    REAL(8),DIMENSION(2)::X,A,B,G1,G,G2,GN,XN,X1
    ! PA‡MEPHOCTœ MACCˆBA BG = N*N
    REAL(8),DIMENSION(2,2)::BG
    REAL(8),DIMENSION(40)::PAR
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    EXTERNAL F,FNLP,GRAD,AGS
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=  1.2
    X(2)=  1.0
! ‡A„AHˆE APAMETPOB METO„A
    Q=0
    PAR(Q+1)=0.00001            ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O HOPME ƒPA„ˆEHTA
    PAR(Q+2)=25                 ! MAKCˆMA‹œHOE —ˆC‹O ˜AƒOB,KOTOPOE MO†HO C„E‹ATœ
    PAR(Q+3)=0                  ! B›XO„HO‰ APAMETP
    PAR(Q+4)=10.                ! PA„ˆ“C HA—A‹œHOƒO ˜APA,OPE„E‹Ÿž™EƒO O‹ACTœ OˆCKA
    PAR(Q+5)=0.001              ! PE˜EHˆŸ O„HOMEPHO‰ ‡A„A—ˆ B›OPA ˜AƒA
    PAR(Q+6)=0.0000000000000001 ! „O“CTˆM›‰ OšEM ‹‹ˆCOˆ„A
    PAR(Q+7)=2                  ! HOMEP BEPCˆˆ METO„A ( =1 „‹Ÿ B›“K‹›X ”“HK–ˆ‰ ; =2, EC‹ˆ ”“HK–ˆŸ HEB›“K‹AŸ )
    PAR(Q+8)=1                  ! OPŸ„OK „ˆ””EPEH–ˆPOBAHˆŸ ( = 1 ˆ‹ˆ 2 )
    PAR(Q+9)=0.00001            ! ˜Aƒ „ˆ””EPEH–ˆPOBAHˆŸ
    PAR(Q+10)=1                 ! —ˆC‹O “„A—H›X ˜AƒOB,—EPE‡ KOTOPOE ‘‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(Q+11)=3                 ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 3 )
! ‚›‡Ž‚ Œ…’Ž„€
    CALL A9 (N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VA9
