! TECTˆPOBAHˆE METO„OB ˆ‡ AKETA M METO„ •“Š€-„†ˆ‚‘€ (AP4)
PROGRAM VAP4
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ ‡A„A—ˆ
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA FUNCTION „‹Ÿ B›—ˆC‹EHˆŸ ‡HA—EHˆŸ KPˆTEPˆŸ
    ! GRAD - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ƒPA„ˆEHTA (HE ˆCO‹œ‡“ETCŸ)
    ! AGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA MATPˆ–› BTOP›X POˆ‡BO„H›X (HE ˆCO‹œ‡“ETCŸ)
    ! Y - ‡HA—EHˆE KPˆTEPˆŸ
    ! G1 - BEKTOP ‡HA—EHˆ‰ POˆ‡BO„H›X ”“HK–ˆˆ F
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 0)
    ! PAR - BEKTOP APAMETPOB METO„A
    ! FNLP - ”ˆKCˆPOBAHHOE ˆMŸ O„POƒPAMM›
! OˆCAHˆE APAMETPOB POƒPAMM› METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /AP41/ X1
    COMMON /AP42/ X2
    COMMON /AP43/ ST
    COMMON /AP44/ SS
    COMMON /AP45/ SF
    REAL(8)::F,FNLP,Y
    INTEGER::Q
    ! PA‡MEPHOCTœ MACCˆBOB X,A,B,G1 PABHA N
    REAL(8),DIMENSION(2)::X,A,B,G1
    REAL(8),DIMENSION(40)::PAR
    ! PA‡MEPHOCTœ BCEX MACCˆBOB = N
    REAL(8),DIMENSION(2)::X1,X2,ST
    INTEGER,DIMENSION(2)::SS,SF
    EXTERNAL F,FNLP,GRAD,AGS
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=-1.0
    X(2)=-1.0
    ! ‹EB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    A(1)=-10.
    A(2)=-10.
    ! PAB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    B(1)=10.
    B(2)=10.
! ‡A„AHˆE APAMETPOB METO„A
    Q=0
    PAR(Q+1)=0.00001 ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ
    PAR(Q+2)=100.    ! MAKCˆMA‹œHOE —ˆC‹O ˜AƒOB,KOTOPOE MO†HO C„E‹ATœ
    PAR(Q+3)=0       ! B›XO„HO‰ APAMETP
    PAR(Q+4)=0.01    ! HA—A‹œH›‰ ˜Aƒ C“CKA
    PAR(Q+5)=0.125   ! KO””ˆ–ˆEHT “MEHœ˜EHˆŸ ˜AƒA
    PAR(Q+6)=0.00001 ! "HEOPE„E‹EHHOCTœ" ‡A„AHˆŸ ƒPAHˆ– APA‹‹E‹EˆE„A
    PAR(Q+ 7)=1      ! —ˆC‹O “„A—H›X ˜AƒOB,—EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR( Q+8)=3      ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ: OT 0 „O 3
! ‚›‡Ž‚ Œ…’Ž„€
    CALL AP4(N,X,A,B,F,GRAD,AGS,Y,G1,Q,PAR,FNLP)
END PROGRAM VAP4
