! ˆCO‹œ‡OBAHˆE METO„OB ˆ‡ AKETA OTˆMˆ‡A–ˆˆ H‹ METO„ HœžTOHA (C8)
PROGRAM VC8
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ BEKTOPA “PAB‹ŸEM›X EPEMEHH›X
    ! L - —ˆC‹O OƒPAHˆ—EHˆ‰ TˆA PABEHCTB
    ! M - O™EE —ˆC‹O OƒPAHˆ—EHˆ‰
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
    ! P - BEKTOP „BO‰CTBEHH›X EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ‡HA—EHˆŸ KPˆTEPˆŸ ˆ OƒPAHˆ—EHˆ‰
    ! CGR - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ƒPA„ˆEHTOB –E‹EBO‰ ”“HK–ˆˆ ˆ OƒPAHˆ—EHˆ‰
    ! CGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA MATPˆ–› BTOP›X POˆ‡BO„H›X –E‹EBO‰ ”“HK–ˆˆ ˆ OƒPAHˆ—EHˆ‰
    ! Y - BEKTOP ‡HA—EHˆ‰ KPˆTEPˆŸ ˆ OƒPAHˆ—EHˆ‰
    ! PAR - BEKTOP APAMETPOB METO„A
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 20)
    ! UNCONS - ˆMŸ O„POƒPAMM› METO„A E‡“C‹OBHO‰ MˆHˆMˆ‡A–ˆˆ
! OˆCAHˆE APAMETPOB POƒPAMM› METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /A1/   M1,N,L
    COMMON /A5/   FUNC
    COMMON /A8/   Y1
    COMMON /A9/   Y2
    COMMON /A10/  NF
    COMMON /A13/  Y11
    COMMON /C80/  ZNFPR
    COMMON /C81/  ACTIV
    COMMON /C82/  XPR
    COMMON /C83/  GR
    COMMON /C84/  HES
    COMMON /C85/  LZ
    COMMON /C86/  LZZ
    COMMON /C87/  NAPR
    COMMON /C88/  DVOY
    COMMON /C89/  DVPR
    COMMON /C801/ LRAB
    COMMON /C802/ MRAB
    ! PA‡MEPHOCTœ MACCˆBOB X,A,B  PABHA  N
    REAL(8),DIMENSION(2)::X,A,B
    ! PA‡MEPHOCTœ MACCˆBA  P   PABHA  M
    REAL(8),DIMENSION(4)::P
    ! PA‡MEPHOCTœ MACCˆBA  Y   PABHA  M1=M+1
    REAL(8),DIMENSION(4)::Y
    REAL(8),DIMENSION(40)::PAR
    ! PA‡MEPHOCTœ  MACCˆBOB GR,XPR  = N
    REAL(8),DIMENSION(2)::XPR,GR
    ! PA‡MEPHOCTœ  MACCˆBOB DVOY,DVPR = M
    REAL(8),DIMENSION(3)::DVOY,DVPR
    ! PA‡MEPHOCTœ  MACCˆBA HES = ( N,N )
    REAL(8),DIMENSION(2,2)::HES
    ! PA‡MEPHOCTœ  MACCˆBA LZZ = ( N+M,N+M )
    REAL(8),DIMENSION(7,7)::LZZ
    ! PA‡MEPHOCTœ  MACCˆBOB LZ,NAPR,LRAB,MRAB = ( N+M )
    REAL(8),DIMENSION(7)::LZ,NAPR,LRAB,MRAB
    ! PA‡MEPHOCTœ  MACCˆBOB Y1,Y2,Y11,FUNC,ZNFPR,ACTIV  = M+1
    REAL(8),DIMENSION(4)::FUNC,Y1,Y2,Y11,ZNFPR
    REAL(8)::F
    INTEGER,DIMENSION(4)::ACTIV
    INTEGER::N,L,M1,Q,M,NF
    EXTERNAL F,CGR,CGS,UNCONS
!
      NF=0
      Q=20
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    M1=4
    M=M1-1
    L=0
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=0.1
    X(2)=0.7
    X(3)=0.2
    ! ‹EB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    A(1)= -100000.
    A(2)= -100000.
    A(3)= -100000.
    ! PAB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    B(1)=100000.
    B(2)=100000.
    B(3)=100000.
! ‡HA—EHˆŸ „BO‰CTBEHH›X EPEMEHH›X
    P(1)=1.D0
    P(2)=1.D0
    P(3)=0.D0
    P(4)=0.D0
    P(5)=0.D0
! ‡A„AHˆE APAMETPOB METO„A
    PAR(1)=0.0001  ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O HOPME ƒPA„ˆEHTA ”“HK–ˆˆ ‹AƒPAH†A
    PAR(2)=15      ! MAKCˆMA‹œHO BO‡MO†HOE —ˆC‹O ˆTEPA–ˆ‰
    PAR(3)=0       ! ”AKTˆ—ECKˆ C„E‹AHHOE —ˆC‹O ˆTEPA–ˆ‰
    PAR(4)=0.8     ! APAMETP B›OPA ˜AƒA „Bˆ†EHˆŸ ( MA†OPAHTA ƒO‹„CTE‰HA )
    PAR(5)=0.01    ! APAMETP B›„E‹EHˆŸ AKTˆBH›X OƒPAHˆ—EHˆ‰
    PAR(6)=0.1     ! ‡HA—EHˆE,PˆCBAˆBAEMOE „BO‰CTBEHH›M EPEMEHH›M, COOTBETCTB“ž™ˆM OƒPAHˆ—EHˆŸM TˆA HEPABEHCTBA, HA—A‹œH›E ‡HA—EHˆŸ KOTOP›X MEHœ˜E 10** ( -18 )
    PAR(7)=0.1     ! MˆHˆMA‹œHOE ‡HA—EHˆE „BO‰CTBEHHO‰ EPEMEHHO‰, Pˆ KOTOPOM OƒPAHˆ—EHˆE TˆA HEPABEHCTBA E™E C—ˆTAETCŸ AKTˆBH›M
    PAR(8)=0.0001  ! ˜Aƒ —ˆC‹EHHOƒO B›—ˆC‹EHˆŸ ƒPA„ˆEHTA
    PAR(9)=2       ! HOMEP PA‡HOCTHO‰ CXEM› —ˆC‹EHHOƒO B›—ˆC‹EHˆŸ ƒPA„ˆEHTA ( = 1 ˆ‹ˆ 2 )
    PAR(10)=0.0001 ! ˜Aƒ —ˆC‹EHHOƒO B›—ˆC‹EHˆŸ ƒECCˆAHA
    PAR(11)=1      ! HOMEP PA‡HOCTHO‰ CXEM› —ˆC‹EHHOƒO B›—ˆC‹EHˆŸ ƒECCˆAHA  ( = 1,2 ˆ‹ˆ 3 )
    PAR(12)=1      ! —ˆC‹O ˜AƒOB,—EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(13)=4      ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 4 )
! ‚›‡Ž‚ Œ…’Ž„€
    CALL C8(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q,UNCONS)
END PROGRAM VC8
