! ˆCO‹œ‡OBAHˆE METO„OB ˆ‡ AKETA OTˆMˆ‡A–ˆˆ H‹ METO„ ‹‹ˆ‘Žˆ„Ž‚ (C9)
PROGRAM VC9
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ BEKTOPA “PAB‹ŸEM›X EPEMEHH›X
    ! L - —ˆC‹O OƒPAHˆ—EHˆ‰ TˆA PABEHCTB
    ! M - O™EE —ˆC‹O OƒPAHˆ—EHˆ‰
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
    ! P - BEKTOP „BO‰CTBEHH›X EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ‡HA—EHˆŸ KPˆTEPˆŸ ˆ OƒPAHˆ—EHˆ‰
    ! CGR - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ƒPA„ˆEHTOB –E‹EBO‰ ”“HK–ˆˆ ˆ OƒPAHˆ—EHˆ‰
    ! CGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA MATPˆ–› BTOP›X POˆ‡BO„H›X –E‹EBO‰ ”“HK–ˆˆ ˆ OƒPAHˆ—EHˆ‰
    ! Y - BEKTOP ‡HA—EHˆ‰ KPˆTEPˆŸ ˆ OƒPAHˆ—EHˆ‰
    ! PAR - BEKTOP APAMETPOB METO„A
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 20)
    ! UNCONS -  ˆMŸ O„POƒPAMM› METO„A E‡“C‹OBHO‰ MˆHˆMˆ‡A–ˆˆ
! OˆCAHˆE APAMETPOB POƒPAMM› METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /A1/  M1,N,L
    COMMON /A2/  XN
    COMMON /A3/  GN
    COMMON /A4/  G
    COMMON /A5/  G2
    COMMON /A6/  BG
    COMMON /A7/  Y1
    COMMON /A8/  Y11
    COMMON /A9/  Y12
    COMMON /A10/ NF
    REAL(8)::F
    INTEGER::N,L,M1,Q,M,NF
    ! PA‡MEPHOCTœ MACCˆBOB X,A,B PABHA N
    REAL(8),DIMENSION(3)::X,A,B
    ! PA‡MEPHOCTœ MACCˆBA P PABHA M
    REAL(8),DIMENSION(5)::P
    ! PA‡MEPHOCTœ MACCˆBA Y PABHA M1=M+1
    REAL(8),DIMENSION(6)::Y
    REAL(8),DIMENSION(40)::PAR
    ! PA‡MEPHOCTœ MACCˆBOB GN,XN,G,G2 = N
    REAl(8),DIMENSION(3)::XN,GN,G,G2
    ! PA‡MEPHOCTœ MACCˆBOB Y1,Y12,Y11 = M+1
    REAl(8),DIMENSION(6)::Y1,Y11,Y12
    ! PA‡MEPHOCTœ MACCˆBA BG = (N,N)
    REAl(8),DIMENSION(9)::BG
    EXTERNAL F,CGR,CGS
!
    NF=0
    Q=20
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    M1=4
    M=M1-1
    L=0
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=0.1
    X(2)=0.7
    ! ‹EB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    A(1)=-100000.
    A(2)=-100000.
    A(3)=-100000.
    ! PAB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    B(1)=100000.
    B(2)=100000.
    B(3)=100000.
! ‡HA—EHˆŸ „BO‰CTBEHH›X EPEMEHH›X
         P(1)=1.D0
         P(2)=1.D0
         P(3)=0.D0
         P(4)=0.D0
         P(5)=0.D0
! ‡A„AHˆE APAMETPOB METO„A
    ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O OšEM“ ‹‹ˆCOˆ„A,
    PAR(1)=0.00000000001 ! ‹OKA‹ˆ‡“ž™EƒO PE˜EHˆE
    PAR(2)=150           ! MAKCˆMA‹œHO BO‡MO†HOE —ˆC‹O ˆTEPA–ˆ‰
    PAR(3)=0.            ! ”AKTˆ—ECKˆ C„E‹AHHOE —ˆC‹O ˆTEPA–ˆ‰
    PAR(4)=1.            ! PA„ˆ“C HA—A‹œHOƒO ˜APA, CO„EP†A™EƒO PE˜EHˆE
    PAR(5)=1.5           ! BEC ˜TPA”A
    PAR(6)=0.001         ! APAMETP PEOPA‡OBAHˆŸ OƒPAHˆ—EHˆ‰ TˆA PABEHCTBA B HEPABEHCTBA
    PAR(7)=0.00001       ! ˜Aƒ —ˆC‹EHHOƒO B›—ˆC‹EHˆŸ ƒPA„ˆEHTA
    PAR(8)=1.            ! HOMEP PA‡HOCTHO‰ CXEM› —ˆC‹EHHOƒO B›—ˆC‹EHˆŸ ƒPA„ˆEHTA ( = 1 ˆ‹ˆ 2 )
    PAR(9)=1.            ! —ˆC‹O ˜AƒOB, —EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(10)=4.           ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 4 )
! ‚›‡Ž‚ Œ…’Ž„€
    CALL C9(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q)
END PROGRAM VC9
