! ˆCO‹œ‡OBAHˆE METO„OB ˆ‡ AKETA OTˆMˆ‡A–ˆˆ ŸŒŽ‰ Œ…’Ž„ ŒŽ„ˆ”ˆ–ˆŽ‚€Ž‰ ”“Š–ˆˆ ‹€ƒ€†€ (CP6)
! („‹Ÿ “„OB‹ETBOPEHˆŸ OƒPAHˆ—EHˆ‰ ˆCO‹œ‡“ETCŸ METO„ E‡“C‹OBHO‰ MˆHˆMˆ‡A–ˆˆ AP3)
PROGRAM VCP6
! XAPAKTEPˆCTˆKA APAMETPOB POƒPAMM› METO„A
    ! N - PA‡MEPHOCTœ BEKTOPA “PAB‹ŸEM›X EPEMEHH›X
    ! L - —ˆC‹O OƒPAHˆ—EHˆ‰ TˆA PABEHCTB
    ! M - O™EE —ˆC‹O OƒPAHˆ—EHˆ‰
    ! X - BEKTOP “PAB‹ŸEM›X EPEMEHH›X
    ! A - BEKTOP ‹EB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹. EPEMEHH›X
    ! B - BEKTOP PAB›X ƒPAHˆ– ˆ‡MEHEHˆŸ “PAB‹.EPEMEHH›X
    ! P - BEKTOP „BO‰CTBEHH›X EPEMEHH›X
    ! F - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ‡HA—EHˆŸ KPˆTEPˆŸ ˆ OƒPAHˆ—EHˆ‰
    ! CGR - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ B›—ˆC‹EHˆŸ ƒPA„ˆEHTOB –E‹EBO‰ ”“HK–ˆˆ ˆ OƒPAHˆ—EHˆ‰
    ! CGS - ˆMŸ O„POƒPAMM› TˆA SUBROUTINE „‹Ÿ PAC—ETA MATPˆ–› BTOP›X POˆ‡BO„H›X –E‹EBO‰ ”“HK–ˆˆ ˆ OƒPAHˆ—EHˆ‰
    ! Y - BEKTOP ‡HA—EHˆ‰ KPˆTEPˆŸ ˆ OƒPAHˆ—EHˆ‰
    ! PAR - BEKTOP APAMETPOB METO„A
    ! Q - APAMETP C ”ˆKCˆPOBAHH›M ‡HA—EHˆEM ( = 20)
    ! AP3 -  ˆMŸ O„POƒPAMM› METO„A E‡“C‹OBHO‰ MˆHˆMˆ‡A–ˆˆ
! OˆCAHˆE APAMETPOB POƒPAMM› METO„A
    ! OˆCAHˆE O™ˆX O‹ACTE‰ METO„A
    COMMON /A1/    M1,N,L
    COMMON /A8/    Y11
    COMMON /A9/    Y2
    COMMON /A10/   NF
    COMMON /A11/   G
    COMMON /CP60/  YYT
    COMMON /CP61/  LX
    COMMON /CP62/  HX
    COMMON /CP63/  GR
    COMMON /CP64/  FG
    COMMON /CP65/  U
    COMMON /CP66/  GU
    COMMON /CP67/  A1
    COMMON /CP68/  B1
    COMMON /CP69/  XX
    COMMON /AGR1/  LX1
    COMMON /AP31/  P1
    COMMON /AP32/  P2
    COMMON /AP33/  G2
    COMMON /AP34/  XV
    COMMON /AP35/  W
    COMMON /AP36/  WN
    COMMON /CPFI2/ AA
    COMMON /CPFI3/ BB
    REAL(8)::F
    INTEGER::N,M,M1,L,Q,NF
    ! PA‡MEPHOCTœ MACCˆBOB X,A,B PABHA N
    REAL(8),DIMENSION(2)::X,A,B
    ! PA‡MEPHOCTœ MACCˆBA P PABHA M
    REAL(8),DIMENSION(5)::P
    ! PA‡MEPHOCTœ MACCˆBA Y PABHA M1=M+1
    REAL(8),DIMENSION(6)::Y
    REAL(8),DIMENSION(40)::PAR
    ! PA‡MEPHOCTœ MACCˆBOB G,GR,LX,HX,XX,AA,BB,LX1 = N
    REAL(8),DIMENSION(2)::G,LX,HX,GR,XX,AA,BB,LX1
    ! PA‡MEPHOCTœ MACCˆBA FG = N*( M+1 )
    REAL(8),DIMENSION(18)::FG
    ! PA‡MEPHOCTœ MACCˆBOB U,GU,A1,B1 = M
    REAL(8),DIMENSION(5)::U,GU,A1,B1
    ! PA‡MEPHOCTœ MACCˆBOB Y11,YYT,Y2S = M+1
    REAL(8),DIMENSION(6)::YYT,Y11,Y2
    ! EPEMEHH›E „‹Ÿ METO„A E‡“C‹OBHO‰ OTˆMˆ‡A–ˆˆ (AP3)
    ! PA‡MEPHOCTœ MACCˆBOB P1,P2,G2,XV,W,WN = max{N,M}
    REAL(8),DIMENSION(6)::P1,P2,G2,XV
    INTEGER,DIMENSION(6)::W,WN
    EXTERNAL F,CGR,CGS,AP3
! 
    NF=0
    Q=20
! ˆCXO„H›E „AHH›E ‡A„A—ˆ
    ! PA‡MEPHOCTœ ‡A„A—ˆ
    M1=4
    M=M1-1
    L=0
    N=2
    ! HA—A‹œHAŸ TO—KA
    X(1)=0.3
    X(2)=0.7
    ! ‹EB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    A(1)=-100000.
    A(2)=-100000.
    ! PAB›E ƒPAHˆ–› “PAB‹. EPEMEHH›X O KA†„O‰ KOOP„ˆHATE
    B(1)=100000.
    B(2)=100000.
! ‡HA—EHˆŸ „BO‰CTBEHH›X EPEMEHH›X
    P(1)=1.D0
    P(2)=1.D0
    P(3)=0.D0
    P(4)=0.D0
    P(5)=0.D0
! ‡A„AHˆE APAMETPOB METO„A
    PAR(1)=0.0001       ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ
    PAR(2)=10.          ! MAKCˆMA‹œHO BO‡MO†HOE —ˆC‹O ˆTEPA–ˆ‰
    PAR(3)=0.           ! ”AKTˆ—ECKˆ C„E‹AHHOE —ˆC‹O ˆTEPA–ˆ‰
    PAR(4)=1.           ! HOMEP BEPCˆˆ METO„A ( = 1,2 ˆ‹ˆ 3 )
    PAR(5)= 0.1         ! APAMETP PEƒ“‹ŸPˆ‡A–ˆˆ
    PAR(6)=0.1          ! BEC OƒPAHˆ—EHˆ‰ B “C‹OBˆˆ OCTAHOBA
    PAR(7)= 0.0001      ! ˜Aƒ B PA‡HOCTHO‰ CXEME —ˆC‹EHHOƒO B›—ˆC‹EHˆŸ ƒPA„ˆEHTA
    PAR(8)=1.           ! HOMEP PA‡HOCTHO‰ CXEM› B›—ˆC‹EHˆŸ ƒPA„ˆEHTA
    PAR(9)=1.           ! —ˆC‹O ˜AƒOB, —EPE‡ KOTOPOE  C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(10)=4.          ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ ( OT 0 „O 4 )
    ! APAMETP› METO„A COPŸ†EHH›X ƒPA„ˆEHTOB (AP3)
    PAR(Q+1)=0.1        ! TO—HOCTœ PE˜EHˆŸ ‡A„A—ˆ O HOPME ƒPA„ˆEHTA
    PAR(Q+2)=100.       ! MAKCˆMA‹œHOE —ˆC‹O ˜AƒOB, KOTOPOE MO†HO C„E‹ATœ
    PAR(Q+3)=0.         ! B›XO„HO‰ APAMETP
    PAR(Q+4)=0.0001     ! HA—A‹œH›‰ ˜Aƒ C“CKA
    PAR(Q+5)=0.1        ! HA—A‹œHAŸ TO—HOCTœ PE˜EHˆŸ O„HOMEPHO‰ ‡A„A—ˆ B›OPA OTˆMA‹œHOƒO ˜AƒA
    PAR(Q+6)=0.00000001 ! MˆHˆMA‹œH›‰ ˜Aƒ C“CKA
    PAR(Q+7)=10.        ! —ˆC‹O ˆTEPA–ˆ‰,—EPE‡ KOTOPOE METO„ "BOCCTAHAB‹ˆBAETCŸ"
    PAR(Q+8)=1.         ! HOMEP BEPCˆˆ METO„A ( = 1 ˆ‹ˆ 2 )
    PAR(Q+9)=1.         ! OPŸ„OK „ˆ””EPEH–ˆPOBAHˆŸ ( = 1 ˆ‹ˆ 2 )
    PAR(Q+10)=0.0001    ! ˜Aƒ „ˆ””EPEH–ˆPOBAHˆŸ
    PAR(Q+11)=1.        ! —ˆC‹O “„A—H›X ˜AƒOB, —EPE‡ KOTOPOE C‹E„“ET B›BO„ˆTœ ˆH”OPMA–ˆž
    PAR(Q+12)=0.        ! CTEEHœ O„POHOCTˆ B›BO„ˆMO‰ ˆH”OPMA–ˆˆ: OT 0 „O 3
! ‚›‡Ž‚ Œ…’Ž„€
    CALL CP6(N,L,M,X,A,B,P,F,CGR,CGS,Y,PAR,Q,AP3)
END PROGRAM VCP6
